[theme]
name = "bad-wolf"

[theme.overrides]
idle_bg = "#333333"
idle_fg = "#dddddd"

good_bg = "#333333"
good_fg = "#dddddd"
warning_bg = "#333333"
warning_fg = "#dddddd"
info_bg = "#333333"
info_fg = "#dddddd"

[icons]
name = "awesome"

[icons.overrides]
backlight_empty = " "
backlight_partial1 = " "
backlight_partial2 = " "
backlight_partial3 = " "
backlight_full = " "

[[block]]
block = "focused_window"
max_width = 21

[[block]]
block = "net"
device = "wlp59s0"
ssid = true
signal_strength = true
hide_inactive = true
ip = true
speed_up = false
speed_down = false
bitrate = false
graph_up = false
interval = 2

[[block]]
block = "sound"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "temperature"
collapsed = false
interval = 10
format = "{average}°C"
chip = "*-isa-*"

[[block]]
block = "battery"
interval = 10
format = "{percentage}% {time}"

[[block]]
block = "backlight"
device = "intel_backlight"
step_width = 1

[[block]]
block = "time"
interval = 1
format = "%a %d.%m.%Y %H:%M:%S"

