[theme]
name = "bad-wolf"

[theme.overrides]
idle_bg = "#333333"
idle_fg = "#dddddd"

good_bg = "#333333"
good_fg = "#dddddd"
warning_bg = "#333333"
warning_fg = "#dddddd"
info_bg = "#333333"
info_fg = "#dddddd"

[icons]
name = "awesome"

[icons.overrides]
backlight_empty = " "
backlight_partial1 = " "
backlight_partial2 = " "
backlight_partial3 = " "
backlight_full = " "

[[block]]
block = "net"
device = "wlan0"
interval = 2
format = "{ssid} {signal_strength} {ip} {speed_down;K*b} {speed_up;K*b} "

# [[block]]
# block = "hueshift"
# hue_shifter = "redshift"
# step = 50
# click_temp = 3500

[[block]]
block = "custom"
command = "echo '\uf0ac ' `curl ifconfig.me`" # assumes fontawesome icons
interval = 600

# [[block]]
# block = "disk_space"
# path = "/home"
# alias = "/"
# info_type = "available"
# unit = "GB"
# interval = 20
# warning = 20.0
# alert = 10.0

# [[block]]
# block = "memory"
# display_type = "memory"
# format_mem = "{mem_used_percents}"
# format_swap = "{swap_used_percents}"

# [[block]]
# block = "cpu"
# interval = 1
#
# [[block]]
# block = "load"
# interval = 1
# format = "{1m}"

[[block]]
block = "sound"

[[block]]
block = "battery"
interval = 10
format = "{percentage} {time}"

[[block]]
block = "time"
interval = 1
format = "%a %d.%m. %H:%M:%S"
